name: 'Accuknox IaC'
description: 'Run Scan against infrastructure as code.'
inputs:
  file:
    description: 'File with infrastructure code or packages to scan'
    required: false
  directory:
    default: '.'
    description: 'Directory with infrastructure code and/or package manager files to scan'
    required: false
  check:
    description: 'Run scan only on a specific check identifier (comma separated)'
    required: false
  skip_check:
    description: 'Run scan on all checks but a specific check identifier (comma separated)'
    required: false
  compact:
    description: 'Do not display code blocks in output'
    required: false
  quiet:
    description: 'display only failed checks'
    required: false
  output_format:
    description: 'The format of the output. cli, json, junitxml, github_failed_only, or sarif (comma separated)'
    required: false
    default: 'json'


branding:
  icon: 'shield'
  color: 'purple'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/bridgecrewio/checkov:3.2.21'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.directory }}
    - ${{ inputs.check }}
    - ${{ inputs.skip_check }}
    - ${{ inputs.compact }}
    - ${{ inputs.quiet }}
    - ${{ inputs.output_format }}
