name: 'Accuknox IaC'
description: 'Run Scan against infrastructure as code.'
inputs:
  file:
    description: 'File with infrastructure code or packages to scan'
    required: false
  directory:
    default: '.'
    description: 'Directory with infrastructure code and/or package manager files to scan'
    required: false
  check:
    description: 'Run scan only on a specific check identifier (comma separated)'
    required: false
  skip_check:
    description: 'Run scan on all checks but a specific check identifier (comma separated)'
    required: false
  compact:
    description: 'Do not display code blocks in output'
    required: false
  quiet:
    description: 'display only failed checks'
    required: false
  output_format:
    description: 'The format of the output. cli, json, junitxml, github_failed_only, or sarif (comma separated)'
    required: false
    default: 'json'
  soft_fail:
    description: 'do not return an error code if there are failed checks'
    required: false
  framework:
    description: 'run only on a specific infrastructure'
    required: false
  skip_framework:
    description: 'skip a specific infrastructure'
    required: false
  github_pat:
    description: 'Environment variable name for a Github personal access token for scanning external modules sourced from private repositories'
    required: false
  soft_fail_on:
    description: 'Do not return an error code only for specific check identifiers (comma separated)'
    required: false
  hard_fail_on:
    description: 'Return an error code only for specific check identifiers (comma separated)'
    required: false
  download_external_modules:
    description: 'download external terraform modules from public git repositories and terraform registry:true, false'
    required: false
  external_checks_dirs:
    description: 'comma separated list of external (custom) checks directories'
    required: false
  enable_secrets_scan_all_files:
    description: 'Scan all files for secrets'
    required: false
  log_level:
    description: 'log level'
    required: false
    default: 'WARNING'
  config_file:
    description: 'checkov configuration file'
    required: false
  baseline:
    description: 'Path to a .checkov.baseline file to compare. Report will include only failed checks that are not in the baseline'
    required: false

    
branding:
  icon: 'shield'
  color: 'purple'

  
runs:
  using: 'docker'
  image: 'docker://ghcr.io/bridgecrewio/checkov:3.2.21'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.directory }}
    - ${{ inputs.check }}
    - ${{ inputs.skip_check }}
    - ${{ inputs.compact }}
    - ${{ inputs.quiet }}
    - ${{ inputs.output_format }}
    - ${{ inputs.soft_fail }}
    - ${{ inputs.framework }}
    - ${{ inputs.skip_framework }}
    - ${{ inputs.external_checks_dirs }}
    - ${{ inputs.external_checks_repos }}
    - ${{ inputs.download_external_modules }}
    - ${{ inputs.enable_secrets_scan_all_files }}    

