name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Run IaC scan
        uses: ./
        with:
          directory: ./
          output_format: json
          soft-fail: 0
          
          # Other optional inputs can be specified here
          
