name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Run IaC scan
        uses: ./
        with:
          file: 'example.tf'               # Provide the path to the file you want to scan
          directory: './'  # Provide the directory where your infrastructure code is located
          compact: 'true'                 # Do not display code blocks in output
          quiet: 'true'                   # Display only failed checks
          output_format: 'json'           # The format of the output
          framework: 'terraform'                # Run only on a specific infrastructure
          skip_framework: 'dockerfile'         # Skip a specific infrastructure
          soft_fail: 'false'              # Do not return an error code if there are failed checks
          github_pat: ${{ secrets.GITHUB_TOKEN }}  # GitHub personal access token for accessing private repositories
          enable_secrets_scan_all_files: 'true'  # Scan all files for secrets
          
  # framework: ansible, argo_workflows, arm, azure_pipelines, bicep, bitbucket_pipelines, cdk, circleci_pipelines, cloudformation, dockerfile, github_configuration, github_actions, gitlab_configuration, gitlab_ci, bitbucket_configuration, helm, json, yaml, kubernetes, kustomize, openapi, sca_package, sca_image, secrets, serverless, terraform, terraform_json, terraform_plan, sast, sast_python, sast_java, sast_javascript, 3d_policy.
